# Ship level module

ch = character()
shipStats = load_json(ch.get_cvar("shipStats","{}"))
dagger = '†'
footer = f"\"{ctx.prefix}ship setup v1.0 | @Corvux\""
tier = ch.levels.total_level - 1
bg = ch.background.split("|")
hdNum = {"small": 3, "medium": 5, "large": 7, "huge": 9, "gargantuan": 11, "tiny": 1}
hdSize = {"tiny": "d4", "small": "d6", "medium": "d8", "large": "d10", "huge": "d12", "gargantuan": "d20"}
pdSize = ["d1","d4","d6","d8","d10","d12"]

def ship_level(args):
    if len(ch.background.split("|")) < 3:
        return err("You're not a ship.....")
    a = argparse(args)

    for cl, lvl in ch.levels:
        type = cl

    base = f'''embed -thumb {ch.image} -color {ch.csettings.color} -footer {footer} -title "Level Summary for {ch.name}" '''
    base += f''' -f "Info|Tier {tier} - {ch.race} {type}" '''

    # Setup Shields
    ch.set_temp_hp(bg[0])
    base += f''' -f "Max Shields|{bg[0]}|inline"'''

    # Hull/Shield Dice
    hdMult = 2 if ch.race.lower() in ["huge", "gargantuan"] else 1
    numDie = (tier * hdMult) + hdNum.get(ch.race.lower(),0)
    hd = f"{hdSize.get(ch.race.lower(),0)}"
    hdName = f"Hull Dice ({hd})"

    shipStats['hdName'] = hdName
    if ch.cc_exists(hdName):
        ch.delete_cc(hdName)

    ch.create_cc_nx(hdName, 0, numDie)

    sdName = f"Shield Dice ({hd})"
    shipStats["sdName"] = sdName
    if ch.cc_exists(sdName):
        ch.delete_cc(sdName)

    ch.create_cc_nx(sdName, 0, numDie)

    base += f''' -f "Hull Die|{numDie}{hd}|inline" -f "Shield Die|{numDie}{hd}|inline" '''

    # Power dice
    pdNum = int(bg[4]) + int(bg[5])
    pdName = f"Power Dice ({pdSize[tier]})"
    shipStats['pdName'] = pdName

    if ch.cc_exists(pdName):
        ch.delete_cc(pdName)

    ch.create_cc_nx(pdName, 0, numDie)

    # Ship Equip Indicator
    shipStats['equip'] = 1

    base += f''' -f "Power Die|{pdNum}{pdSize[tier]}|inline" '''

    ch.set_cvar("shipStats", dump_json(shipStats))

    return base

