# TODO [Resolute Bestiary - Ground]: E-XD-Series Infiltrator Droid (Strike)
# TODO [Resolute Bestiary - Ground]: Trooper, Shadow (Burst)
# TODO [Resolute Bestiary - Ground]: Trooper, Shadow (Flash Grenade (recharge 5-6))
# TODO [Resolute Bestiary - Ground]: Possessed Hunter (Shield Bash)
# TODO [Resolute Bestiary - Ground]: Trooper, EVO (Burst)
# TODO [Resolute Bestiary - Ground]: Trooper, EVO (Flechette Cannon)
# TODO [Resolute Bestiary - Ground]: Trooper, Shadow EVO (Burst)
# TODO [Resolute Bestiary - Ground]: Trooper, Shadow EVO (Flechette Cannon)
# TODO [Resolute Bestiary - Ground]: Cultist, Electromancer (Charged Touch)
# TODO [Resolute Bestiary - Ground]: Cultist, Master (Charged Touch)
# TODO [Resolute Bestiary - Ground]: Roggwart (Claw)
# TODO [Resolute Bestiary - Ground]: Roggwart (Frightening Presence)
# TODO [Resolute Bestiary - Ground]: Fireteam: Trooper (Massed Fire)
# TODO [Resolute Bestiary - Ground]: Trooper, Demolitions (Fragmentation Grenade (3/day))
# TODO [Resolute Bestiary - Ground]: Trooper, Demolitions (Set Mine (2/day))
# TODO [Resolute Bestiary - Ground]: Trooper, Demolitions (Breaching Charge (2/day))
# TODO [Resolute Bestiary - Ground]: Squad: Trooper, Demolitions (Fragmentation Grenades (6/day))
# TODO [Resolute Bestiary - Ground]: Squad: Trooper, Demolitions (Set Mine (4/day))
# TODO [Resolute Bestiary - Ground]: Squad: Trooper, Demolitions (Breaching Charge (4/day))
# TODO [Resolute Bestiary - Ground]: Fireteam: Trooper, Flame (Flamethrower)
# TODO [Resolute Bestiary - Ground]: Squad: Trooper, Flame (Flamethrower)
# TODO [Resolute Bestiary - Ground]: Yevethan Commando (Dewclaw)
# TODO [Resolute Bestiary - Ground]: Yevethan Supercommando (Dewclaw)
# TODO [Resolute Bestiary - Space]: TIE/IN New Republic (old) (Missile launcher (4/day))
# TODO [Resolute Bestiary - Space]: Z-95-NR Headhunter (old) (Missile Launcher (8/day))
# TODO [Resolute Bestiary - Space]: TIE/sa Bomber (old) (Missile Launcher - Rapid)
# TODO [Resolute Bestiary - Space]: TIE/sa Bomber (old) (Missile Launcher - Burst)
# TODO [Resolute Bestiary - Space]: TIE/sa Bomber (old) (Bomb Deployer)
# TODO [Resolute Bestiary - Non Canon]: Jetstream Szam (Unarmed Strike)
