# TODO [Resolute 2.0 Bestiary]: ISB Officer (Rally Troops (Recharge 5-6))
# TODO [Resolute 2.0 Bestiary]: Purge Trooper (Volley (Recharge 6))
# TODO [Resolute 2.0 Bestiary]: Trooper, Technician (Repair (Recharge 5-6))
# TODO [Resolute 2.0 Bestiary]: Elite Purge Trooper (Volley (Recharge 6))
# TODO [Resolute Bestiary - Space]: TIE/IN New Republic (old) (Missile launcher (4/day))
# TODO [Resolute Bestiary - Space]: Z-95-NR Headhunter (old) (Missile Launcher (8/day))
# TODO [Resolute Bestiary - Space]: TIE/sa Bomber (old) (Missile Launcher - Rapid)
# TODO [Resolute Bestiary - Space]: TIE/sa Bomber (old) (Missile Launcher - Burst)
# TODO [Resolute Bestiary - Space]: TIE/sa Bomber (old) (Bomb Deployer)
# TODO [Resolute Bestiary - Non Canon]: Jetstream Szam (Unarmed Strike)
