# TODO: Flexible Rending
# TODO: Force Frustrater
# TODO: Heat Shielded
# TODO: Metabolic Tolerance
# TODO: Mindful Meditator
# TODO: Mounted Caster
# TODO: Multiclass Improvement
# TODO: Overwhelming Presence
# TODO: Quick Caster
# TODO: Sniping Caster
# TODO: Spiritual Techcaster
# TODO: Splashclass Improvement
# TODO: Titan's Power
# TODO: Total Reconstruction
# TODO: Two-Weapon Casting
# TODO: Unnatural Resilience
# TODO: Versatile Withering
# TODO: Vigorous Virility
# TODO: War Caster
# TODO: Well-Insulated