# TODO: Multiclass Improvement
# TODO: Overwhelming Presence
# TODO: Quick Caster
# TODO: Sniping Caster
# TODO: Spiritual Techcaster
# TODO: Splashclass Improvement
# TODO: Titan's Power
# TODO: Total Reconstruction
# TODO: Two-Weapon Casting
# TODO: Unnatural Resilience
# TODO: Versatile Withering
# TODO: Vigorous Virility
# TODO: War Caster
# TODO: Well-Insulated
# TODO: Area Mastery
# TODO: Assisting Mastery
# TODO: Berserk Mastery
# TODO: Blindfighting Mastery
# TODO: Brawler Mastery
# TODO: Counterstrike Mastery
# TODO: Covert Mastery
# TODO: Defense Mastery
# TODO: Disruption Mastery
# TODO: Dual Wield Mastery
# TODO: Duelist Mastery
# TODO: Equilibrium Mastery
# TODO: Explosives Mastery
# TODO: Formation Mastery
# TODO: Formfighting Mastery
# TODO: Great Weapon Mastery
# TODO: Guerrilla Mastery
# TODO: Gunning Mastery
# TODO: Mounted Mastery
# TODO: Onslaught Mastery
# TODO: Poisoner Mastery
# TODO: Secured Mastery
# TODO: Sentinel Mastery
# TODO: Sharpshooter Mastery
# TODO: Shield Mastery
# TODO: Snapshot Mastery
# TODO: Split Mastery
# TODO: Spotting Mastery
# TODO: Superiority Mastery
# TODO: Throwing Mastery
# TODO: Twin-Blade Mastery
# TODO: Versatile Mastery
# TODO: Area Style
# TODO: Assisting Style
# TODO: Berserk Style
# TODO: Blindfighting Style
# TODO: Brawler Style
# TODO: Counterstrike Style
# TODO: Covert Style
# TODO: Defense Style
# TODO: Disruption Style
# TODO: Dual Wield Style
# TODO: Duelist Style
# TODO: Equilibrium Style
# TODO: Explosives Style
# TODO: Formation Style
# TODO: Formfighting Style
# TODO: Great Weapon Style
# TODO: Guerrilla Style
# TODO: Gunning Style
# TODO: Mounted Style
# TODO: Onslaught Style
# TODO: Poisoner Style
# TODO: Secured Style
# TODO: Sentinel Style
# TODO: Sharpshooter Style
# TODO: Shield Style
# TODO: Snapshot Style
# TODO: Split Style
# TODO: Spotting Style
# TODO: Superiority Style
# TODO: Throwing Style
# TODO: Twin-Blade Style
# TODO: Versatile Style
# TODO: Aqinos Form
# TODO: Ataru Form
# TODO: Bakuuni Hand Form
# TODO: Djem So Form
# TODO: Drallig Form
# TODO: Ishu Form
# TODO: Jar'Kai Form
# TODO: Juyo Form
# TODO: Makashi Form
# TODO: Niman Form
# TODO: Shien Form
# TODO: Shii-Cho Form
# TODO: Sokan Form
# TODO: Soresu Form
# TODO: Trakata Form
# TODO: Trispzest Form
# TODO: Twilight Form
# TODO: Vaapad Form
# TODO: Vonil Form
# TODO: Ysannanite Form